apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
type: Opaque
StringData:
  # base64 encoded => echo -n '<value>' | base64
  AIRFLOW__LOGGING__REMOTE_LOGGING: False
  # Logging
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID:
  AIRFLOW__LOGGING__DELETE_LOCAL_LOGS: False
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER:
  # SMTP
  AIRFLOW__SMTP__SMTP_HOST:
  AIRFLOW__SMTP__SMTP_PORT: "123"
  AIRFLOW__SMTP__SMTP_MAIL_FROM:
  AIRFLOW__SMTP__SMTP_STARTTLS: "false"
  AIRFLOW__SMTP__SMTP_SSL: "false"
  # Proxy - Those values are read in constants.py file
  AIRFLOW_PROXY:
  AIRFLOW_USER_AGENT:
  # Apache polaris & MinIO - Nubonyxia context
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
