apiVersion: v2
name: airflow
description: Airflow umbrella chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: airflow
  version: 1.22.0
  repository: https://airflow.apache.org
