apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
spec:
  destination:
    namespace: "user-ytihianine"
    server: https://kubernetes.default.svc
  source:
    path: argocd/airflow
    repoURL: https://github.com/ytihianine/la-suite-donnee.git
    targetRevision: openmetadata
    helm:
      valueFiles:
        - values-prod.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
