apiVersion: v2
name: secret-operator
description: Vault Secret Operator umbrella chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: vault-secrets-operator
  version: 1.4.1
  repository: https://helm.releases.hashicorp.com
