secret-operator:
  # Top level configuration for the vault secrets operator deployment.
  # This consists of a controller and a kube rbac proxy container.
  controller:
    # Set the number of replicas for the operator.
    # @type: integer
    replicas: 1

    # Configures the PodDisruptionBudget for the controller deployment.
    podDisruptionBudget:

      # Toggles the deployment of the PodDisruptionBudget for the controller.
      # @type: boolean
      enabled: false

    # Settings related to the vault-secrets-operator container.
    manager:
      # Image sets the repo and tag of the vault-secrets-operator image to use for the controller.
      image:
        pullPolicy: IfNotPresent
        repository: hashicorp/vault-secrets-operator
        tag: 1.4.0

      # Global secret transformation options. In addition to the boolean options
      # below, these options may be set via the
      # `VSO_GLOBAL_TRANSFORMATION_OPTIONS` environment variable as a
      # comma-separated list. Valid values are: `exclude-raw`
      globalTransformationOptions:
        # excludeRaw directs the operator to prevent _raw secret data being stored
        # in the destination K8s Secret.
        excludeRaw: false

      # Global Vault auth options. In addition to the boolean options
      # below, these options may be set via the
      # `VSO_GLOBAL_VAULT_AUTH_OPTIONS` environment variable as a
      # comma-separated list. Valid values are: `allow-default-globals`
      globalVaultAuthOptions:
        # allowDefaultGlobals directs the operator search for a "default"
        # VaultAuthGlobal if none is specified on the referring VaultAuth CR.
        # Default: true
        # @type: boolean
        allowDefaultGlobals: true

      # Defines the maximum number of concurrent reconciles for each controller.
      # May also be set via the `VSO_MAX_CONCURRENT_RECONCILES` environment variable.
      #
      # default: 100
      # @type: integer
      maxConcurrentReconciles:

      kubeClient:
        # QPS indicates the maximum QPS to the kubernetes API.
        # When the value is 0, the kubernetes client's default is used.
        # May also set via the `VSO_KUBE_CLIENT_QPS` environment variable.
        # Default: 0
        # @type: float
        qps:

        # Maximum burst for throttling requests to the kubernetes API.
        # When the value is 0, the kubernetes client's default is used.
        # May also set via the `VSO_KUBE_CLIENT_BURST` environment variable.
        # Default: 0
        # @type: uint
        burst:

      # Defines additional environment variables to be added to the
      # vault-secrets-operator manager container.
      # Example:
      #
      # ```yaml
      # extraEnv:
      #   - name: HTTP_PROXY
      #     value: http://proxy.example.com
      #   - name: VSO_OUTPUT_FORMAT
      #     value: json
      #   - name: VSO_CLIENT_CACHE_SIZE
      #     value: "20000"
      #   - name: VSO_CLIENT_CACHE_PERSISTENCE_MODEL
      #     value: "direct-encrypted"
      #   - name: VSO_MAX_CONCURRENT_RECONCILES
      #     value: "30"
      # ```
      # @type: array<map>
      extraEnv: []

      # Configures the default resources for the vault-secrets-operator container.
      # For more information on configuring resources, see the K8s documentation:
      # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
      # @recurse: true
      # @type: map
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 64Mi

  # Configures the default VaultConnection CR which will be used by resources
  # if they do not specify a VaultConnection reference. The name is 'default' and will
  # always be installed in the same namespace as the operator.
  # NOTE:
  # * It is strongly recommended to deploy the vault secrets operator in a secure Vault environment
  #   which includes a configuration utilizing TLS and installing Vault into its own restricted namespace.
  defaultVaultConnection:
    # toggles the deployment of the VaultAuthMethod CR
    # @type: boolean
    enabled: true


  # Configures and deploys the default VaultAuthMethod CR which will be used by resources
  # if they do not specify a VaultAuthMethod reference. The name is 'default' and will
  # always be installed in the same namespace as the operator.
  # NOTE:
  # * It is strongly recommended to deploy the vault secrets operator in a secure Vault environment
  #   which includes a configuration utilizing TLS and installing Vault into its own restricted namespace.
  defaultAuthMethod:
    # toggles the deployment of the VaultAuthMethod CR
    # @type: boolean
    enabled: true

    # Vault namespace for the VaultAuthMethod CR
    # @type: string
    namespace: "projet-mef-sg-dsci"

    # Kubernetes namespace glob patterns which are allow-listed for use with the default AuthMethod.
    # @type: array<string>
    allowedNamespaces: []

    # Vault Auth method to be used with the VaultAuthMethod CR
    # @type: string
    method: kubernetes

    # Mount path for the Vault Auth Method.
    # @type: string
    mount: kubernetes

    # Vault Kubernetes auth method specific configuration
    kubernetes:
      # Vault Auth Role to use
      # This is a required field and must be setup in Vault prior to deploying the helm chart
      # if `defaultAuthMethod.enabled=true`
      # @type: string
      role: ""

      # Kubernetes ServiceAccount associated with the default Vault Auth Role
      # @type: string
      serviceAccount: default

      # Token Audience should match the audience of the vault kubernetes auth role.
      # @type: array<string>
      tokenAudiences: []

    # VaultAuthGlobalRef
    vaultAuthGlobalRef:
      #  toggles the inclusion of the VaultAuthGlobal configuration in the
      # default VaultAuth CR.
      # @type: boolean
      enabled: false

  # Configures a Prometheus ServiceMonitor
  telemetry:
    serviceMonitor:
      # The Prometheus operator *must* be installed before enabling this feature,
      # if not the chart will fail to install due to missing CustomResourceDefinitions
      # provided by the operator.
      #
      # Instructions on how to install the Helm chart can be found here:
      #  https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
      # More information can be found here:
      #  https://github.com/prometheus-operator/prometheus-operator
      #  https://github.com/prometheus-operator/kube-prometheus

      # Enable deployment of the Vault Secrets Operator ServiceMonitor CustomResource.
      # @type: boolean
      enabled: false

  # Configure the behaviour of Helm hooks.
  hooks:
    # Resources common to all hooks.
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    # Configure the Helm pre-upgrade hook that handles custom resource definition (CRD) upgrades.
    upgradeCRDs:
      # Set to true to automatically upgrade the CRDs.
      # Disabling this will require manual intervention to upgrade the CRDs, so it is recommended to
      # always leave it enabled.
      # @type: boolean
      enabled: true

      # Limit the number of retries for the CRD upgrade.
      # @type: integer
      backoffLimit: 5

      # Set the timeout for the CRD upgrade. The operation should typically take less than 5s
      # to complete.
      # @type: string
      executionTimeout: 30s

  csi:
    # Only supports Vault Enterprise servers.
    # Toggles the deployment of the Vault Secrets Operator CSI driver. Setting `enabled` to `true`
    # deploys the CSI driver and the necessary resources to the cluster.
    # @type: boolean
    enabled: false

  ## Used by unit tests, and will not be rendered except when using `helm template`, this can be safely ignored.
  tests:
    # @type: boolean
    enabled: false
