apiVersion: v1
kind: Secret
metadata:
  name: db-config-secret
type: Opaque
stringData:
  # Authentication
  POSTGRES_ADMIN_PASSWORD: pg_admin
  POSTGRES_USER_PASSWORD: pg_admin
  POSTGRES_REPLICATION_PASSWORD: pg_replication_admin