apiVersion: v1
kind: Secret
metadata:
  name: db-config-secret
type: Opaque
stringData:
  # Authentication
  POSTGRES_ADMIN_PASSWORD: demo_config_admin
  POSTGRES_USER_PASSWORD: demo_config_user
  POSTGRES_REPLICATION_PASSWORD: demo_config_replication
