apiVersion: v2
name: trino
description: Trino umbrella chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: trino 
  version: 1.42.2
  repository: https://trinodb.github.io/charts/
