trino:
  # Default values for trino.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  image:
    # -- Image registry, defaults to empty, which results in DockerHub usage
    registry: ""
    # -- Repository location of the Trino image, typically `organization/imagename`
    repository: ghcr.io/ytihianine/trino-custom
    # -- Image tag, defaults to the Trino release version specified as `appVersion` from Chart.yaml
    tag: "latest"
    # -- Optional digest value of the image specified as `sha256:abcd...`. A specified value overrides `tag`.
    digest: ""
    # -- When true, only the content in `repository` is used as image reference
    useRepositoryAsSoleImageReference: false
    pullPolicy: IfNotPresent

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      argocd.argoproj.io/ignore-healthcheck: "true"
    hosts:
      - host: trino.lab.sspcloud.fr
        paths:
          - path: /
            pathType: ImplementationSpecific
    # ingress.hosts -- [Ingress
    # rules](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules).
    # @raw
    # Example:
    # ```yaml
    #  - host: trino.example.com
    #    paths:
    #      - path: /
    #        pathType: ImplementationSpecific
    # ```
    tls: []
    # ingress.tls -- Ingress
    # [TLS](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls)
    # configuration.
    # @raw
    # Example:
    # ```yaml
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
    # ```

  server:
    workers: 1
    node:
      # server.node.environment -- Supports templating with `tpl`.
      environment: production
      dataDir: /data/trino
      pluginDir: /usr/lib/trino/plugin
    log:
      trino:
        level: INFO
    config:
      path: /etc/trino
      https:
        enabled: false
        port: 8443
        keystore:
          path: ""
      # -- Trino supports multiple [authentication
      # types](https://trino.io/docs/current/security/authentication-types.html):
      # PASSWORD, CERTIFICATE, OAUTH2, JWT, KERBEROS, HEADER.
      authenticationType: ""
      query:
        maxMemory: "4GB"

    # server.autoscaling -- Configure [Horizontal Pod Autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
    # for workers (`server.keda.enabled` must be `false`).
    autoscaling:
      enabled: true

    # server.keda -- Configure [Kubernetes Event-driven Autoscaling](https://keda.sh/) for workers
    # (`server.autoscaling.enabled` must be `false`).
    keda:
      enabled: false

  accessControl: {}
  # accessControl -- [System access
  # control](https://trino.io/docs/current/security/built-in-system-access-control.html)
  # configuration.
  # @raw
  # Set the type property to either:
  # * `configmap`, and provide the rule file contents in `rules`,
  # * `properties`, and provide configuration properties in `properties`.
  # Properties example:
  # ```yaml
  # type: properties
  # properties: |
  #     access-control.name=custom-access-control
  #     access-control.custom_key=custom_value
  # ```
  # Config map example:
  # ```yaml
  #  type: configmap
  #  refreshPeriod: 60s
  #  # Rules file is mounted to /etc/trino/access-control
  #  configFile: "rules.json"
  #  rules:
  #    rules.json: |-
  #      {
  #        "catalogs": [
  #          {
  #            "user": "admin",
  #            "catalog": "(mysql|system)",
  #            "allow": "all"
  #          },
  #          {
  #            "group": "finance|human_resources",
  #            "catalog": "postgres",
  #            "allow": true
  #          },
  #          {
  #            "catalog": "hive",
  #            "allow": "all"
  #          },
  #          {
  #            "user": "alice",
  #            "catalog": "postgresql",
  #            "allow": "read-only"
  #          },
  #          {
  #            "catalog": "system",
  #            "allow": "none"
  #          }
  #        ],
  #        "schemas": [
  #          {
  #            "user": "admin",
  #            "schema": ".*",
  #            "owner": true
  #          },
  #          {
  #            "user": "guest",
  #            "owner": false
  #          },
  #          {
  #            "catalog": "default",
  #            "schema": "default",
  #            "owner": true
  #          }
  #        ]
  #      }
  # ```

  additionalConfigProperties:
    - http-server.process-forwarded=IGNORE
  # additionalConfigProperties -- [Additional config
  # properties](https://trino.io/docs/current/admin/properties.html).
  # @raw
  # Example:
  # ```yaml
  #  - internal-communication.shared-secret=random-value-999
  #  - http-server.process-forwarded=true
  # ```

  catalogs:
    data_store: |
      connector.name=iceberg
      iceberg.catalog.type=rest
      iceberg.rest-catalog.uri=https://polaris-catalog.lab.incubateur.finances.rie.gouv.fr/api/catalog
      iceberg.rest-catalog.oauth2.server-uri=https://polaris-catalog.lab.incubateur.finances.rie.gouv.fr/api/catalog/v1/oauth/tokens
      iceberg.rest-catalog.warehouse=cat_data_store
      iceberg.rest-catalog.security=OAUTH2
      iceberg.rest-catalog.oauth2.credential=03387f626ba573f4:44b779068d36bba032f2cb3155fc47e9
      iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL
      iceberg.rest-catalog.nested-namespace-enabled=true
      iceberg.rest-catalog.vended-credentials-enabled=false
      fs.native-s3.enabled=true
      s3.endpoint=https://minio.lab.incubateur.finances.rie.gouv.fr
      s3.region=us-east-1
      s3.aws-access-key=eDP3WTVueohsfQdrwA2z
      s3.aws-secret-key=JlU7Prvpdt7XQoACP4QF6Thfqv2RJqe0QLq3GOdS
      s3.path-style-access=true
    tpcds: |
      connector.name=tpcds
      tpcds.splits-per-node=4

    tpch: |
      connector.name=tpch
      tpch.splits-per-node=4
  # catalogs -- Configure
  # [catalogs](https://trino.io/docs/current/installation/deployment.html#catalog-properties).
  # @raw
  # Example:
  # ```yaml
  #  objectstore: |
  #    connector.name=iceberg
  #    iceberg.catalog.type=glue
  #  jmx: |
  #    connector.name=memory
  #  memory: |
  #    connector.name=memory
  #    memory.max-data-per-node=128MB
  # ```
  # Supports templating with `tpl`.


  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false

  coordinator:
    deployment:
      annotations: {}
      progressDeadlineSeconds: 600
      # coordinator.deployment.progressDeadlineSeconds -- The maximum time in seconds for a deployment to make progress before it
      # is considered failed. The deployment controller continues to
      # process failed deployments and a condition with a ProgressDeadlineExceeded
      # reason is surfaced in the deployment status.

      revisionHistoryLimit: 1
      # coordinator.deployment.revisionHistoryLimit -- The number of old ReplicaSets to retain to allow rollback.

      strategy: {}
      # coordinator.deployment.strategy -- The deployment strategy to use to replace existing pods with new ones.

    jvm:
      maxHeapSize: "8G"
      minHeapSize:
      maxHeapPercent:
      # coordinator.jvm.maxHeapPercent -- Alternative method of setting heap size as a percentage of container memory limits, which is recommended for better JVM ergonomics. `maxHeapSize` must be unset for this to work.
      initialHeapPercent:
      # coordinator.jvm.initialHeapPercent -- sets the starting heap size as a percentage of container memory limits.
      #
      # NOTE: to disable dynamic heap resizing when setting the size as a percent, add `-XX:MaxHeapFreeRatio=100` or `-XX:-UseAdaptiveSizePolicy` to `additionalJVMConfig`.
      gcMethod:
        type: "UseG1GC"
        g1:
          heapRegionSize: "32M"

    config:
      memory:
        heapHeadroomPerNode: ""
      nodeScheduler:
        includeCoordinator: false
        # coordinator.config.nodeScheduler.includeCoordinator -- Allows scheduling work on the coordinator so that a
        # single machine can function as both coordinator and worker. For large clusters, processing work on the
        # coordinator can negatively impact query performance because the machine's resources are not available for the
        # critical coordinator tasks of scheduling, managing, and monitoring query execution.
      query:
        maxMemoryPerNode: "4GB"

  worker:
    deployment:
      annotations: {}
      progressDeadlineSeconds: 600
      # worker.deployment.progressDeadlineSeconds -- The maximum time in seconds for a deployment to make progress before it
      # is considered failed. The deployment controller continues to
      # process failed deployments and a condition with a ProgressDeadlineExceeded
      # reason is surfaced in the deployment status.

      revisionHistoryLimit: 1
      # worker.deployment.revisionHistoryLimit -- The number of old ReplicaSets to retain to allow rollback.

    jvm:
      maxHeapSize: "8G"
      minHeapSize:
      maxHeapPercent:
      # jvm.maxHeapPercent -- Alternative method of setting heap size as a percentage of container memory limits, which is recommended for better JVM ergonomics. `maxHeapSize` must be unset for this to work.
      initialHeapPercent:
      # jvm.initialHeapPercent -- sets the starting heap size as a percentage of container memory limits.
      #
      # NOTE: to disable dynamic heap resizing when setting the size as a percent, add `-XX:MaxHeapFreeRatio=100` or `-XX:-UseAdaptiveSizePolicy` to `additionalJVMConfig`.
      gcMethod:
        type: "UseG1GC"
        g1:
          heapRegionSize: "32M"

    config:
      memory:
        heapHeadroomPerNode: ""
      query:
        maxMemoryPerNode: "4GB"

    gracefulShutdown:
      enabled: false
