apiVersion: v1
kind: Secret
metadata:
  name: polaris-secret
type: Opaque
stringData:
  # Database
  # If using postgresql, the following environment variables must be set in the secret:
  DB_USER: your_token
  DB_PASSWORD: your_token
  DB_JDBC_URL: jdbc:postgresql://polaris-postgresql:5432/polaris
  # If using MongoDB, the following environment variables must be set
  # S3
  AWS_ACCESS_KEY_ID: your_token
  AWS_SECRET_ACCESS_KEY: your_token
