apiVersion: v2
name: polaris
description: Apache Polaris umbrella chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: polaris
  version: 46.163.1
  repository: https://downloads.apache.org/polaris/helm-chart
