apiVersion: v2
name: openmetadata
description: OpenMetaData umbrella chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: openmetadata
  version: 2.0.1
  repository: https://helm.open-metadata.org/
