apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
type: Opaque
StringData:
  # Security
  fernet-key: verySecureFernetKey
  api-secret-key: verySecureApiSecretKey
  jwt-secret: verySecureJWTToken
  # Config & Metadata database
  # The 'connection' key is a SQLAlchemy connection string, e.g.:
  #   postgresql+psycopg2://airflow:password@postgres/airflow
  connection: postgresql+psycopg2://airflow:password@postgres/airflow
  # Logging
  AIRFLOW__LOGGING__REMOTE_LOGGING: False
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID:
  AIRFLOW__LOGGING__DELETE_LOCAL_LOGS: False
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER:
  # SMTP
  AIRFLOW__SMTP__SMTP_HOST:
  AIRFLOW__SMTP__SMTP_PORT: "123"
  AIRFLOW__SMTP__SMTP_MAIL_FROM:
  AIRFLOW__SMTP__SMTP_STARTTLS: "false"
  AIRFLOW__SMTP__SMTP_SSL: "false"
  # Proxy - Those values are read in constants.py file
  AIRFLOW_PROXY:
  AIRFLOW_USER_AGENT:
  # Apache polaris & MinIO - Nubonyxia context
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  # GitSync - Only if repository is private and requires HTTP Basic authentication
  #    GIT_SYNC_USERNAME: <base64_encoded_git_username>
  #    GIT_SYNC_PASSWORD: <base64_encoded_git_password>
  #    # For git-sync v4
  #    GITSYNC_USERNAME: <base64_encoded_git_username>
  #    GITSYNC_PASSWORD: <base64_encoded_git_password>