apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-config-prod
spec:
  destination:
    namespace: ""
    server: https://kubernetes.default.svc
  source:
    path: argocd/postgres/config
    repoURL: https://github.com/ytihianine/la-suite-donnee.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prod.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
