apiVersion: v1
kind: Secret
metadata:
  name: openmetadata-secret
type: Opaque
stringData:
  # Security
  fernet-key: verySecureFernetKey
  # Database
  sql-password: openmetadata_password
  # Elasticsearch
  elasticsearch-password: openmetadata_password
  # Airflow
  airflow-password: airflow_password
