apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secretstore
  namespace: projet-mef-sg-dsci
spec:
  provider:
    vault:
      server: "https://vault.lab.sspcloud.fr"
      path: "secret"
      version: "v2"
      auth:
        # static token: https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-secret"
          key: "VAULT_TOKEN"
