apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
type: Opaque
stringData:
  # Your git token to access private repositories, base64 encoded => echo -n '<token>' | base64
  VAULT_ADDR: "https://vault.lab.sspcloud.fr"
  VAULT_TOKEN: "s.1234567890abcdef"
