---
- name: Add repo to ArgoCD
  ansible.builtin.command: |
    argocd repo add {{ item.url }} _
      --username {{ item.username }} --password {{ item.password }} \
      --proxy {{ item.proxy | default('') }} --no-proxy {{ item.no_proxy | default('') }}
  loop: "{{ repo | default([]) }}"
