apiVersion: v2
name: opensearch
description: OpenSearch umbrella chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: opensearch
    version: 2.35.1
    repository: https://opensearch-project.github.io/helm-charts/
