# =================
# Values
# =================
dbConfig:
  enable: true
  auth:
    host: localhost
    port: 5432
    name: postgres
    user: postgres
    password: postgres

  # 1. Créer les bases de données avec le compte admin cluster
  databases:
    - name: test_airflow_config
      comment: "Contient toute la configuration d'Airflow (DAGs, connections, variables, etc.)"
    - name: test_superset_config
      comment: "Contient toute la configuration de Superset (dashboards, charts, etc.)"

  # 2. Créer les roles (NOLOGIN) avec le compte admin cluster, puis accorder leurs privilèges
  roles:
    - name: airflow_admin_role
      comment: "Role admin pour gérer la base de données de configuration d'Airflow"
      privileges:
        - privs: ALL
          type: database
          objs: test_airflow_config
          grant_option: true
    - name: superset_admin_role
      comment: "Role admin pour gérer la base de données de configuration de Superset"
      privileges:
        - privs: ALL
          type: database
          objs: test_superset_config
          grant_option: true

  # 3. Créer les utilisateurs (LOGIN) avec le compte admin cluster, puis leur attribuer leurs appartenances aux roles
  users:
    - name: airflow_admin_user
      password: airflow_password
      comment: "Utilisateur de la base de données de configuration d'Airflow"
      member_of:
        - airflow_admin_role
    - name: superset_admin_user
      password: superset_password
      comment: "Utilisateur de la base de données de configuration de Superset"
      member_of:
        - superset_admin_role

dbData:
  enable: true
  auth:
    host: localhost
    port: 5432
    name: postgres
    user: postgres
    password: postgres

  databases:
    - name: data_store
      comment: "Database data_store qui contient toutes les données métiers"

  roles:
    - name: analyst_role
      comment: "Role analyste pour accéder à la base de données métier. Lecture seule des données."
      privileges:
        - privs: SELECT
          type: database
          objs: data_store
          grant_option: true

  users:
    - name: analyst_superset
      password: analyst_password
      comment: "Utilisateur analyste pour accéder à la base de données métier"
      member_of:
        - analyst_role
