renovate:

  image:
    # -- Registry to pull image from
    registry: ghcr.io
    # -- Image name to pull
    repository: renovatebot/renovate
    # -- Renovate image tag to pull
    tag: 43.184.0
    # -- "IfNotPresent" to pull the image if no image with the specified tag exists on the node, "Always" to always pull the image or "Never" to try and use pre-pulled images
    pullPolicy: IfNotPresent
    # -- Set `true` to use the full image. See <https://docs.renovatebot.com/getting-started/running/#the-full-image>
    useFull: false

  cronjob:
    # -- Schedules the job to run using cron notation
    schedule: '0 */4 * * *'  # Every 4 hours
    # -- Amount of failed jobs to keep in history
    failedJobsHistoryLimit: '3'
    # -- Amount of completed jobs to keep in history
    successfulJobsHistoryLimit: '3'

  renovate:
    # -- Custom exiting global renovate config
    existingConfigFile: ''
    # See https://docs.renovatebot.com/self-hosted-configuration
    config: |
      {
        "platform": "github",
        "endpoint": "https://api.github.com",
        "gitAuthor": "Renovate Bot <renovate[bot]@users.noreply.github.com>",
        "autodiscover": true,
        "autodiscoverFilter": ["ytihianine/*"],
        "dryRun": null,
        "rebaseWhen": "behind-base-branch",
        "requireConfig": "optional",
        "onboardingConfig": {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": ["config:recommended"]
        },
        "packageRules": [
          {
            "matchManagers": ["pip_requirements", "pipenv", "poetry"],
            "groupName": "python dependencies"
          },
          {
            "matchManagers": ["npm", "yarn", "pnpm"],
            "groupName": "node dependencies"
          },
          {
            "matchManagers": ["dockerfile", "docker-compose"],
            "groupName": "docker dependencies"
          },
          {
            "matchManagers": ["github-actions"],
            "groupName": "github actions"
          },
          {
            "matchManagers": ["helm-values", "helmv3"],
            "groupName": "helm dependencies"
          }
        ]
      }

    # Instead of a file system cache, it is highly recommended to use SQLite.
    # Take a look at https://github.com/renovatebot/renovate/discussions/30525 for more information.
    # -- Options related to persistence
    persistence:
      cache:
        # -- Allow the cache to persist between runs
        enabled: false

  ssh_config:
    # -- Whether to enable the use and creation of a secret containing .ssh files
    enabled: false

  # -- Environment variables to add from existing secrets/configmaps. Uses the keys as variable name
  envFrom:
  - secretRef:
      name: renovatebot-secret
