# List of repo to add

# Template
# repo:
#   - url: ""
#     name: ""
#     project: ""
#     username: ""
#     password: ""
#     proxy: "" # Laisser vide si pas de proxy
#     no_proxy: "" # Laisser vide si pas de no_proxy

repo: []
