apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset-mef
spec:
  destination:
    namespace: projet-mef-sg-dsci
    server: https://kubernetes.default.svc
  source:
    path: argocd/superset
    repoURL: https://github.com/ytihianine/deploiement-application.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prod.yaml
      fileParameters:
        - name: superset.configOverrides.config_override
          path: superset_config_override.py
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
