superset:

  onyxia:
    friendlyName: superset
    owner: custom
    share: true
    userDefinedValues: ""

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      # The hostname for the web Ingress (templated)
      - superset.lab.sspcloud.fr

  image:
    repository: ghcr.io/ytihianine/apache-superset-custom
    tag: e025702
    pullPolicy: IfNotPresent

  # -- Same as above but the values are files
  configOverridesFiles: {}

  bootstrapScript: |
    #!/bin/bash
    if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

  init:
    jobAnnotations:
      "helm.sh/hook": post-install,post-upgrade
      "helm.sh/hook-delete-policy": "before-hook-creation"
      "argocd.argoproj.io/hook": Sync
      "argocd.argoproj.io/hook-delete-policy": HookSucceeded
    loadExamples: false
    createAdmin: true
    adminUser:
      firstname: Superset
      lastname: Admin
      email: admin@superset.com
      username: superset_admin
      password: superset_admin

  extraSecretEnv:
    SUPERSET_SECRET_KEY: supersetSecretKey
  supersetNode:
    replicas:
      enabled: true
      replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80
    connections:
      db_host: db-config-prod-postgresql
      db_port: 5432
      db_user: superset_admin_user
      db_pass: superset_password
      db_name: superset_config
  ## Set to false if bringing your own PostgreSQL.
  postgresql:
    enabled: false
  # Superset Celery worker configuration
  supersetWorker:
    replicas:
      enabled: true
      replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80
    # -- Sets the [pod disruption budget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) for supersetWorker pods
    resources:
      limits:
        cpu: 4000m
        memory: 12288Mi
      requests:
        cpu: 2000m
        memory: 6144Mi
