apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
type: Opaque
StringData:
  # Security
  SUPERSET_SECRET_KEY: verySecureKey
  # MAPBOX_API_KEY: # Only for v6 previous versions
  # SMTP - only work with config override
  SUPERSET_SMTP_HOST: "localhost"
  SUPERSET_SMTP_STARTTLS: true
  SUPERSET_SMTP_SSL: false
  SUPERSET_SMTP_USER: "superset"
  SUPERSET_SMTP_PORT: 25
  SUPERSET_SMTP_PASSWORD: "superset"
  SUPERSET_SMTP_MAIL_FROM: "superset@superset.com"
  SMTP_SSL_SERVER_AUTH: false
  # Database & Redis auth from secrets are not supported yet
