name: Build and Push custom trino image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'images/trino/**'

env:
  TRINO_VERSION: ${{ vars.TRINO_VERSION }}
  IMAGE_NAME: ghcr.io/${{ github.repository }}/trino

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -f images/trino/Dockerfile
          --build-arg TRINO_VERSION=${{ env.TRINO_VERSION }}
          -t ${{ env.IMAGE_NAME }}:${{ env.TRINO_VERSION }}-${GITHUB_SHA::7} .

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.TRINO_VERSION }}-${GITHUB_SHA::7}
