name: Build and Push custom airflow image

on:
  workflow_dispatch:
    inputs:
      airflow_version:
        description: 'Airflow version to build (leave empty to use Dockerfile default)'
        required: false
        type: string

  push:
    branches:
      - main
    paths:
      - 'images/airflow/**'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/apache-airflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Get Airflow version
        id: version
        shell: bash
        run: |
          if [ -n "${{ inputs.airflow_version }}" ]; then
            VERSION="${{ inputs.airflow_version }}"
          else
            VERSION=$(grep -E '^ARG AIRFLOW_VERSION=' images/airflow/Dockerfile | cut -d= -f2)
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Airflow version: $VERSION"

      - name: Set image tag
        id: tag
        shell: bash
        run: |
          SUFFIX=""

          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
            SUFFIX="-test"
          fi

          echo "suffix=$SUFFIX" >> "$GITHUB_OUTPUT"
          echo "Image suffix: $SUFFIX"

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" |
            docker login ghcr.io \
              -u "${{ github.actor }}" \
              --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -f images/airflow/Dockerfile \
            --build-arg AIRFLOW_VERSION=${{ steps.version.outputs.version }} \
            -t ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}${{ steps.tag.outputs.suffix }}-${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push \
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}${{ steps.tag.outputs.suffix }}-${{ github.sha }}
